// Copyright 2018 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package terraformutils

import (
	"context"

	"github.com/zclconf/go-cty/cty"
)

type ProviderGenerator interface {
	Init(args []string) error
	InitService(serviceName string, verbose bool) error
	GetName() string
	GetService() ServiceGenerator
	GetConfig() cty.Value
	GetBasicConfig() cty.Value
	GetSupportedService() map[string]ServiceGenerator
	GenerateFiles()
	GetProviderData(arg ...string) map[string]interface{}
	GenerateOutputPath() error
	GetResourceConnections() map[string]map[string][]string
}

type ProviderWithSource interface {
	GetSource() string
}

// ProviderWithImportIDs maps a listed resource to the ID Terraform imports it
// with (--engine=terraform), for listers that record a different ID. ok is
// false for resource types Terraform can't import.
type ProviderWithImportIDs interface {
	ImportID(r Resource) (id string, ok bool)
}

// ProviderWithChildImports lists, for --engine=terraform, resources that
// hold parts of r's configuration the provider manages as separate
// resources, such as an S3 bucket's versioning. They are imported next to
// r. It returns no children for most resources.
type ProviderWithChildImports interface {
	ChildImports(ctx context.Context, r Resource) ([]Resource, error)
}

// ProviderWithOmittedArguments names, per resource type or under "*" for
// all, arguments that configuration generated by --engine=terraform must
// leave out: arguments a child resource (see ProviderWithChildImports)
// manages, or that only repeat what the provider configuration sets.
// They must be computed, so that leaving them out changes no plan.
type ProviderWithOmittedArguments interface {
	OmittedArguments() map[string][]string
}

// ProviderWithStateOnlyArguments names, per resource type, arguments the
// provider keeps only in state: AWS doesn't report them, so they are unset
// after an import and the first apply records their defaults without
// calling the cloud. The verification gate lets plans change them.
type ProviderWithStateOnlyArguments interface {
	StateOnlyArguments() map[string][]string
}

// ProviderWithSelectionDefaults names the listed resources a selection
// leaves out unless told otherwise, by "type id", with the reason:
// resources the cloud creates and manages itself, such as a default VPC.
type ProviderWithSelectionDefaults interface {
	ExcludedByDefault(ctx context.Context, resources []Resource) (map[string]string, error)
}

// ProviderWithScope names the account (or subscription or project) and the
// region an import covers, for the output layout
// ({output}/{provider}/{account}/{region}/): one root per state
// boundary.
type ProviderWithScope interface {
	Scope(ctx context.Context) (account, region string, err error)
}

// ProviderWithDefaultTags describes how the provider applies tags to every
// resource, for --engine=terraform to move the tags all resources share
// into the provider configuration: the resources' tags attribute, the
// provider block that applies tags (AWS: default_tags), and the key prefix
// of tags the cloud sets itself, which can't be applied that way.
type ProviderWithDefaultTags interface {
	DefaultTags() (attribute, block, reservedPrefix string)
}

type Provider struct {
	Service ServiceGenerator
	Config  cty.Value
}

func (p *Provider) Init(args []string) error {
	panic("implement me")
}

func (p *Provider) GetConfig() cty.Value {
	return p.Config
}

func (p *Provider) GetName() string {
	panic("implement me")
}

func (p *Provider) InitService(serviceName string) error {
	panic("implement me")
}

func (p *Provider) GenerateOutputPath() error {
	panic("implement me")
}

func (p *Provider) GenerateFiles() {
	panic("implement me")
}

func (p *Provider) GetService() ServiceGenerator {
	return p.Service
}

func (p *Provider) GetSupportedService() map[string]ServiceGenerator {
	panic("implement me")
}

func (p *Provider) GetBasicConfig() cty.Value {
	return cty.ObjectVal(map[string]cty.Value{})
}

// DataSource reads one resource: the data source's type and the argument
// that takes the resource's import ID.
type DataSource struct {
	Type, Argument string
}

// ProviderWithDataSources names, per resource type, the data source that
// reads one resource by its import ID, for --engine=terraform to refer to
// resources the selection leaves out, such as a default VPC.
type ProviderWithDataSources interface {
	DataSources() map[string]DataSource
}
